-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.7
-- Tue Mar 03 10:30:34 2026

-- parameterized module component declaration
component pll_24m93
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll_24m93
    port map (CLKI=>__, CLKOP=>__, LOCK=>__);
