-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 3.9
-- Wed Mar 04 11:27:13 2026

-- parameterized module component declaration
component SPRAM
    port (Address: in  std_logic_vector(9 downto 0); 
        Data: in  std_logic_vector(15 downto 0); Clock: in  std_logic; 
        WE: in  std_logic; ClockEn: in  std_logic; 
        Q: out  std_logic_vector(15 downto 0));
end component;

-- parameterized module component instance
__ : SPRAM
    port map (Address(9 downto 0)=>__, Data(15 downto 0)=>__, Clock=>__, 
        WE=>__, ClockEn=>__, Q(15 downto 0)=>__);
