-- VHDL testbench template generated by SCUBA Diamond (64-bit) 3.14.0.75.2
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.std_logic_unsigned.all;

use IEEE.math_real.all;

use IEEE.numeric_std.all;

entity tb is
end entity tb;


architecture test of tb is 

    component SPRAM
        port (Address : in std_logic_vector(9 downto 0); 
        Data : in std_logic_vector(15 downto 0); Clock: in std_logic; 
        WE: in std_logic; ClockEn: in std_logic; 
        Q : out std_logic_vector(15 downto 0)
    );
    end component;

    signal Address : std_logic_vector(9 downto 0) := (others => '0');
    signal Data : std_logic_vector(15 downto 0) := (others => '0');
    signal Clock: std_logic := '0';
    signal WE: std_logic := '0';
    signal ClockEn: std_logic := '0';
    signal Q : std_logic_vector(15 downto 0);
begin
    u1 : SPRAM
        port map (Address => Address, Data => Data, Clock => Clock, WE => WE, 
            ClockEn => ClockEn, Q => Q
        );

    process

    begin
      Address <= (others => '0') ;
      wait for 100 ns;
      wait for 10 ns;
      for i in 0 to 2054 loop
        wait until Clock'event and Clock = '1';
        Address <= Address + '1' after 1 ns;
      end loop;
      wait;
    end process;

    process

    begin
      Data <= (others => '0') ;
      wait for 100 ns;
      wait for 10 ns;
      for i in 0 to 1027 loop
        wait until Clock'event and Clock = '1';
        Data <= Data + '1' after 1 ns;
      end loop;
      wait;
    end process;

    Clock <= not Clock after 5.00 ns;

    process

    begin
      WE <= '0' ;
      wait for 10 ns;
      for i in 0 to 1027 loop
        wait until Clock'event and Clock = '1';
        WE <= '1' after 1 ns;
      end loop;
      WE <= '0' ;
      wait;
    end process;

    process

    begin
      ClockEn <= '0' ;
      wait for 100 ns;
      wait for 10 ns;
      ClockEn <= '1' ;
      wait;
    end process;

end architecture test;
